version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    default_assignees:
      - "tokuda109"
    ignored_updates:
      - match:
          dependency_name: "next"
